"""empty message

Revision ID: 217c2bc959b3
Revises: 263dec48ea7f
Create Date: 2022-08-23 16:53:04.241096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217c2bc959b3'
down_revision = '263dec48ea7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('product_detail', sa.Text(), nullable=True),
    sa.Column('alergy_dai', sa.Boolean(), nullable=True),
    sa.Column('alergy_cru', sa.Boolean(), nullable=True),
    sa.Column('alergy_nut', sa.Boolean(), nullable=True),
    sa.Column('alergy_pch', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('create_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_date')
    op.drop_table('products')
    # ### end Alembic commands ###
