"""empty message

Revision ID: 5bae48d49b38
Revises: 217c2bc959b3
Create Date: 2022-08-23 17:07:42.276082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bae48d49b38'
down_revision = '217c2bc959b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birth',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birth',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
